version: 0.2

phases:
  build:
    commands:
      - echo "Build started"
  post_build:
    commands:
      - echo "Deployment started"
      - aws elasticbeanstalk update-environment --environment-name modern-marvel-dev --version-label app-v0_1_1-33-g6b2d-230508_112658125940






